### ISSUE TITLE
About LSTM in loc-net

### ISSUE THREAD

**Issue by jugg1024** [Bartzi/stn-ocr#14]
1. Why lstm is used in loc-net ?
    i saw in the paper: "This BLSTM is used to generate the hidden states hn, which in turn are used to predict the affine transformation matrices". Why not directly use Flattened feature to predict the output affine transformation matrices.
2. Why lstm input  is same? 
    In the code, the Flattened feature is copied for num_timestep times as for num_timestep inputs of lstm, these features are totally the same, why design it in such way? And if so, the diverse direction in blstm should be useless.
3. How to choose output matrices.
   If bbox is less than num_timestep, then how do i find which affine transformation matrices is the perferred bbox parameters. 
can you explain it to me?  I am a little bit confused about the paper!

**Comment by Bartzi** [comment]
We are using a LSTM in the localization net because we want to find more than one region of text in the image.

Imagine we would not use a LSTM here. The localization network would produce a set of features that will be passed to the fully connected layer, which predicts the transformation parameters. This will work, but the transformation parameters will either be parameters that lead to cropping one line of text or one character from the image, leaving all the others untouched. It could also lead to transformation parameters that make the image sampler crop all text lines at once from the image.

We do not want any of this. We want to have transformation parameters that tell the image sampler to only sample at points, that either belong to a single word or character (depending on the task we want to solve).
This is also the reason why the input to our LSTM is always the 'same'. We want the LSTM to concentrate on all extracted features and produce a set of transformation parameters for each text region, at each timestep. The difference in input is the hidden state of the LSTM. This hidden state contains enough information for the LSTM to know which region of text to predict as the next region. Because of that we can also see that the reverse direction is not useless, as it supplies global information to the first timestep of the LSTM and helps in creating a better transformation parameter estimation.

Your third question:
The number of timesteps should always be set to the number of bboxes you want to find, as the system predicts transformation parameters for a text region at each timestep.

Does that make it a little bit clearer?

**Comment by jugg1024** [comment]
@Bartzi very clearly，thanks. 
so the hidden state together with next input tells which region have been predicted, and which region of text should be the next to predict. Can i understand it in such way ...?

And about the third question, if i can not know how much text region is contained in the photo, maybe at most 3. then how should i set number of timesteps~  if it's set to 3, when the real number of text is less than 3, for example, only one text.  What are the outputs shall look like, will all of transformation parameters refer to same region .

**Comment by Bartzi** [comment]
I think you can think of the LSTM in that way.

Regarding the number of timesteps: This is still an open problem! Right now we have no way of knowing how many lines of text are in the image. We therefore fix the number of timesteps to a reasonable value. The network will then learn to cope with iamges that contain less text regions, but this is actually not a perfect solution. It would be better to let the localization network decide by itself, when to stop. So something like adaptive computation time might come in handy here. But we did not try anything like that, yet.

But if you want to try anything like that, I would be very happy to see that :smile:

**Comment by jugg1024** [comment]
@Bartzi Really appreciate for your explanation
